version: '3'
services:
  mysql:
    image: leafney/alpine-mariadb:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PWD=123456
      - MYSQL_USER_DB=bookstore
    volumes:
      - $PWD/.data/mysql:/var/lib/mysql
